services:
  - type: worker
    name: discord-japan-bot
    env: python
    buildCommand: pip install -r dependencies.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: RENDER
        value: "true"
    plan: free